/*
static enum e_CASHSHOP_ACK npc_cashshop_process_payment(struct npc_data *nd, int price, int points, struct map_session_data *sd) {
	int cost[2] = { 0, 0 };

	npc_shop_currency_type(sd, nd, cost, false);

	switch(nd->subtype) {
*/
		//////////////////////////////
		/// Barter Shop BACHNT
		//////////////////////////////
		case NPCTYPE_EXBARTERSHOP:
			break;
		case NPCTYPE_BARTERSHOP:
			break;
		//////////////////////////////