	
/*	
	/// NPC Subtype

enum npc_subtype : uint8{
	NPCTYPE_WARP, /// Warp
	NPCTYPE_SHOP, /// Shop
	NPCTYPE_SCRIPT, /// Script
	NPCTYPE_CASHSHOP, /// Cashshop
	NPCTYPE_ITEMSHOP, /// Itemshop
	NPCTYPE_POINTSHOP, /// Pointshop
	NPCTYPE_TOMB, /// Monster tomb
	NPCTYPE_MARKETSHOP, /// Marketshop
*/
	/// Barter Shop [BACHNT]
	NPCTYPE_BARTERSHOP, /// Barter Shop
	NPCTYPE_EXBARTERSHOP, /// Expanded Barter Shop