REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_alchemist`,`job_assassin`,`job_blacksmith`,`job_crusader`,`job_knight`,`job_supernovice`,`class_third`,`class_third_upper`,`class_third_baby`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (1320,'Diva_Axe','Diva Axe','Weapon','1hAxe',1800,180,110,1,1,true,true,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n bonus bBaseAtk,30;\n bonus bHit,5;\n}\nif (.@r>=9) {\n bonus bBaseAtk,30;\n bonus bHit,5;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_alchemist`,`job_assassin`,`job_blacksmith`,`job_crusader`,`job_knight`,`job_supernovice`,`class_third`,`class_third_upper`,`class_third_baby`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (1325,'Mirage_Axe','Mirage Axe','Weapon','1hAxe',1800,180,110,5,1,true,true,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n bonus bBaseAtk,30;\n bonus bHit,5;\n}\nif (.@r>=9) {\n bonus bBaseAtk,30;\n bonus bHit,5;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_crusader`,`job_knight`,`job_swordman`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (1444,'Spear_of_Trust','Thunder Spear','Weapon','1hSpear',2000,140,3,3,true,true,true,true,3,50,true,'.@r = getrefine();\nbonus bAtkEle,Ele_Wind;\nif (.@r>=7) {\n .@val = 10;\n if (.@r>=9)\n .@val += 15;\n bonus2 bAddEle,Ele_Water,.@val;\n bonus2 bAddRace,RC_Fish,.@val;\n}');


REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_monk`,`job_priest`,`class_third`,`class_third_upper`,`class_third_baby`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (1842,'Diva_Claw','Diva Claw','Weapon',400,140,100,1,1,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_monk`,`job_priest`,`class_third`,`class_third_upper`,`class_third_baby`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (1843,'Mirage_Claw','Mirage Claw','Weapon',400,140,100,5,1,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_barddancer`,`class_third`,`class_third_upper`,`class_third_baby`,`gender`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (1945,'Diva_Viollin','Diva Viollin','Weapon','Musical',250,180,120,1,1,true,true,true,true,'Male',true,4,150,true,'.@r = getrefine();\nif (.@r>=7)\n   bonus2 bSkillAtk,"CG_ARROWVULCAN",150;\nif (.@r>=9)\n   bonus2 bSkillAtk,"CG_ARROWVULCAN",50;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_barddancer`,`class_third`,`class_third_upper`,`class_third_baby`,`gender`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (1946,'Mirage_Viollin','Mirage Viollin','Weapon','Musical',250,180,120,5,1,true,true,true,true,'Male',true,4,150,true,'.@r = getrefine();\nif (.@r>=7)\n   bonus2 bSkillAtk,"CG_ARROWVULCAN",150;\nif (.@r>=9)\n   bonus2 bSkillAtk,"CG_ARROWVULCAN",50;');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_monk`,`job_priest`,`job_sage`,`job_soullinker`,`job_supernovice`,`job_wizard`,`class_third`,`class_third_upper`,`class_third_baby`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (2035,'Diva_Staff','Diva Staff','Weapon','2hStaff',2400,120,270,1,1,true,true,true,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nbonus bHealPower,2*.@r;\nif (.@r>=7)\n   bonus bMatkRate,4;\nif (.@r>=9)\n   bonus bMatkRate,4;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_monk`,`job_priest`,`job_sage`,`job_soullinker`,`job_supernovice`,`job_wizard`,`class_third`,`class_third_upper`,`class_third_baby`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (2036,'Mirage_Staff','Mirage Staff','Weapon','2hStaff',2400,120,270,5,1,true,true,true,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nbonus bHealPower,2*.@r;\nif (.@r>=7)\n   bonus bMatkRate,4;\nif (.@r>=9)\n   bonus bMatkRate,4;');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`location_right_accessory`,`location_left_accessory`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_nocart`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (2751,'Academy_Badge','Academy Of Badge','Armor',100,true,true,100,true,true,true,true,true,true,'bonus bInt,2;\nbonus bMatkRate,3;\nbonus bMaxHP,100;');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`defense`,`slots`,`location_head_top`,`equip_level_min`,`refineable`,`view`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_nosell`,`trade_nocart`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (5603,'RTC_Winner_Only','RTC First Place','Armor',250,8,1,true,1,true,577,100,true,true,true,true,true,true,true,'bonus bAllStats,3;\nbonus bAspdRate,10;\nbonus bFixedCast,-500;\nbonus2 bAddRace,RC_DemiHuman,10;\nbonus2 bMagicAddRace,RC_DemiHuman,10;\nbonus2 bAddRace,RC_Player_Human,10;\nbonus2 bMagicAddRace,RC_Player_Human,10;\nbonus bUnbreakableHelm;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`defense`,`slots`,`location_head_top`,`equip_level_min`,`refineable`,`view`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_nosell`,`trade_nocart`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (5604,'RTC_Second_Best','RTC Second Place','Armor',250,6,1,true,1,true,578,100,true,true,true,true,true,true,true,'bonus bAllStats,2;\nbonus bAspdRate,7;\nbonus bFixedCast,-300;\nbonus2 bAddRace,RC_DemiHuman,5;\nbonus2 bMagicAddRace,RC_DemiHuman,5;\nbonus2 bAddRace,RC_Player_Human,5;\nbonus2 bMagicAddRace,RC_Player_Human,5;\nbonus bUnbreakableHelm;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`defense`,`slots`,`location_head_top`,`equip_level_min`,`refineable`,`view`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_nosell`,`trade_nocart`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (5605,'RTC_Third_Best','RTC Third Place','Armor',250,4,1,true,1,true,579,100,true,true,true,true,true,true,true,'bonus bAllStats,1;\nbonus bAspdRate,5;\nbonus bFixedCast,-100;\nbonus2 bAddRace,RC_DemiHuman,3;\nbonus2 bMagicAddRace,RC_DemiHuman,3;\nbonus2 bAddRace,RC_Player_Human,3;\nbonus2 bMagicAddRace,RC_Player_Human,3;\nbonus bUnbreakableHelm;');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_gunslinger`,`job_rebellion`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (13130,'Gun_of_Trust','Thunder Gun','Weapon','Revolver',1000,60,7,2,true,true,true,true,3,50,true,'.@r = getrefine();\nbonus bAtkEle,Ele_Wind;\nif (.@r>=7) {\n .@val = 10;\n if (.@r>=9)\n .@val += 15;\n bonus2 bAddEle,Ele_Water,.@val;\n bonus2 bAddRace,RC_Fish,.@val;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_rebellion`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (13140,'Diva_Handgun','Diva Handgun','Weapon','Revolver',350,70,7,1,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_rebellion`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (13141,'Mirage_Handgun','Mirage Handgun','Weapon','Revolver',350,70,7,1,true,true,true,4,150,true,'.@r = getrefine();\nbonus bBaseAtk,2*getskilllv("GS_SNAKEEYE");\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_kagerouoboro`,`job_ninja`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (13333,'Diva_Huuma','Diva Huuma','Weapon','Huuma',1500,150,160,3,1,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_kagerouoboro`,`job_ninja`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (13334,'Mirage_Huuma','Mirage Huuma','Weapon','Huuma',1500,150,160,5,1,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_alchemist`,`job_blacksmith`,`job_crusader`,`job_knight`,`class_third`,`class_third_upper`,`class_third_baby`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (13466,'Diva_Blade','Diva Blade','Weapon','1hSword',1200,150,130,1,1,true,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_alchemist`,`job_blacksmith`,`job_crusader`,`job_knight`,`class_third`,`class_third_upper`,`class_third_baby`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (13467,'Mirage_Blade','Mirage Blade','Weapon','1hSword',1200,150,130,5,1,true,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`defense`,`slots`,`location_armor`,`equip_level_min`,`refineable`,`script`) VALUES (15187,'Diva_Robe','Diva Robe','Armor',1000,80,1,true,150,true,'.@r = getrefine();\nif (.@r>=7)\n   bonus bHPrecovRate,10;\nif (.@r>=9)\n   bonus bHPrecovRate,20;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`defense`,`slots`,`location_armor`,`equip_level_min`,`refineable`,`script`) VALUES (15188,'Mirage_Robe','Mirage Robe','Armor',1000,80,1,true,150,true,'.@r = getrefine();\nif (.@r>=7)\n   bonus bSPrecovRate,10;\nif (.@r>=9)\n   bonus bSPrecovRate,20;');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_acolyte`,`job_alchemist`,`job_blacksmith`,`job_crusader`,`job_knight`,`job_merchant`,`job_monk`,`job_novice`,`job_priest`,`job_supernovice`,`job_swordman`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (16049,'Mace_of_Trust','Thunder Hammer','Weapon','Mace',2000,130,1,3,true,true,true,true,true,true,true,true,true,true,true,true,3,50,true,'.@r = getrefine();\nbonus bAtkEle,Ele_Wind;\nbonus bUnbreakableWeapon;\nif (.@r>=7) {\n .@val = 10;\n if (.@r>=9)\n .@val += 15;\n bonus2 bAddEle,Ele_Water,.@val;\n bonus2 bAddRace,RC_Fish,.@val;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_alchemist`,`job_blacksmith`,`job_crusader`,`job_knight`,`job_monk`,`job_priest`,`job_supernovice`,`class_third`,`class_third_upper`,`class_third_baby`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (16058,'Diva_Mace','Diva Mace','Weapon','Mace',1500,150,110,1,1,true,true,true,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_alchemist`,`job_blacksmith`,`job_crusader`,`job_knight`,`job_monk`,`job_priest`,`job_supernovice`,`class_third`,`class_third_upper`,`class_third_baby`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (16059,'Mirage_Mace','Mirage Mace','Weapon','Mace',1500,150,110,5,1,true,true,true,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_archer`,`job_barddancer`,`job_hunter`,`job_rogue`,`job_thief`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (18133,'Bow_of_Trust','Thunder Bow','Weapon','Bow',1500,120,5,2,true,true,true,true,true,true,true,3,50,true,'.@r = getrefine();\nbonus bAtkEle,Ele_Wind;\nif (.@r>=7) {\n .@val = 10;\n if (.@r>=9)\n .@val += 15;\n bonus2 bAddEle,Ele_Water,.@val;\n bonus2 bAddRace,RC_Fish,.@val;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_barddancer`,`job_hunter`,`job_rogue`,`class_third`,`class_third_upper`,`class_third_baby`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (18146,'Diva_Wing','Diva Wing','Weapon','Bow',900,160,170,5,1,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_barddancer`,`job_hunter`,`job_rogue`,`class_third`,`class_third_upper`,`class_third_baby`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (18147,'Mirage_Wing','Mirage Wing','Weapon','Bow',900,160,170,5,1,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nbonus bBaseAtk,2*getskilllv("AC_VULTURE");\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`location_costume_head_top`,`location_costume_head_Mid`,`location_costume_head_Low`,`equip_level_min`,`view`,`trade_override`,`trade_nodrop`,`script`) VALUES (19567,'C_Hatta_Black','Costume Hatta Black','Armor',true,true,true,1,676,100,true,'bonus bVit,1;');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`defense`,`slots`,`location_garment`,`equip_level_min`,`refineable`,`script`) VALUES (20827,'Diva_Manteau','Diva Manteau','Armor',600,15,1,true,150,true,'.@r = getrefine();\nif (.@r>=7)\n   bonus bMaxHPrate,5;\nif (.@r>=9)\n   bonus bMaxHPrate,10;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`defense`,`slots`,`location_garment`,`equip_level_min`,`refineable`,`script`) VALUES (20828,'Mirage_Manteau','Mirage Manteau','Armor',600,15,1,true,150,true,'.@r = getrefine();\nif (.@r>=7)\n   bonus bMaxSPrate,5;\nif (.@r>=9)\n   bonus bMaxSPrate,10;');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_crusader`,`job_knight`,`class_third`,`class_third_upper`,`class_third_baby`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (21026,'Diva_Claymore','Diva Claymore','Weapon','2hSword',3400,280,230,1,1,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_crusader`,`job_knight`,`class_third`,`class_third_upper`,`class_third_baby`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (21027,'Mirage_Claymore','Mirage Claymore','Weapon','2hSword',3400,280,230,5,1,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`defense`,`job_kagerouoboro`,`job_rebellion`,`location_shoes`,`equip_level_min`,`refineable`,`script`) VALUES (22107,'Modify_Str_Boots','Modified Str Boots','Armor',20,600,25,true,true,true,99,true,'.@r = getrefine();\nbonus bMaxHP,300+(100*(.@r/3));\nbonus bMaxSP,30+(10*(.@r/3));\nbonus bBaseAtk,7*(.@r/3);\nif (readparam(bStr)>=120)\n bonus bBaseAtk,50;');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`defense`,`slots`,`location_shoes`,`equip_level_min`,`refineable`,`script`) VALUES (22127,'Diva_Shoes','Diva Shoes','Armor',600,10,1,true,150,true,'.@r = getrefine();\nif (.@r>=7)\n   bonus bMaxHP,1000;\nif (.@r>=9)\n   bonus bMaxHP,2000;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`defense`,`slots`,`location_shoes`,`equip_level_min`,`refineable`,`script`) VALUES (22128,'Mirage_Shoes','Mirage Shoes','Armor',600,10,1,true,150,true,'.@r = getrefine();\nif (.@r>=7)\n  bonus bMaxSP,100;\nif (.@r>=9)\n   bonus bMaxSP,200;');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_crusader`,`job_knight`,`class_third`,`class_third_upper`,`class_third_baby`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (26004,'Diva_Lance','Diva Lance','Weapon','2hSpear',3500,200,230,3,1,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_crusader`,`job_knight`,`class_third`,`class_third_upper`,`class_third_baby`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (26005,'Mirage_Lance','Mirage Lance','Weapon','2hSpear',3500,200,230,5,1,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_monk`,`job_priest`,`job_sage`,`job_soullinker`,`job_supernovice`,`job_wizard`,`class_third`,`class_third_upper`,`class_third_baby`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (26105,'Diva_Wand','Diva Wand','Weapon','Staff',300,60,180,1,1,true,true,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nbonus bHealPower,2*.@r;\nif (.@r>=7)\n   bonus bMatkRate,4;\nif (.@r>=9)\n   bonus bMatkRate,4;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_monk`,`job_priest`,`job_sage`,`job_soullinker`,`job_supernovice`,`job_wizard`,`class_third`,`class_third_upper`,`class_third_baby`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (26106,'Mirage_Wand','Mirage Wand','Weapon','Staff',300,60,180,5,1,true,true,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nbonus bHealPower,2*.@r;\nif (.@r>=7)\n   bonus bMatkRate,4;\nif (.@r>=9)\n   bonus bMatkRate,4;');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_summoner`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (26143,'Diva_Foxtail','Diva Foxtail','Weapon','Staff',400,150,180,1,1,true,true,4,150,true,'.@r = getrefine();\nbonus bHealPower,2*.@r;\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n   bonus bMatkRate,4;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n   bonus bMatkRate,4;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_summoner`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (26144,'Mirage_Foxtail','Mirage Foxtail','Weapon','Staff',400,150,180,5,1,true,true,4,150,true,'.@r = getrefine();\nif (getskilllv("SU_SOULATTACK") == 1) {\n  bonus bBaseAtk,20;\n}\nbonus bHealPower,2*.@r;\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n   bonus bMatkRate,4;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n   bonus bMatkRate,4;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_barddancer`,`class_third`,`class_third_upper`,`class_third_baby`,`gender`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (26201,'Diva_Blade_Whip','Diva Blade Whip','Weapon','Whip',500,150,120,2,1,true,true,true,true,'Female',true,4,150,true,'.@r = getrefine();\nif (.@r>=7)\n   bonus2 bSkillAtk,"CG_ARROWVULCAN",150;\nif (.@r>=9)\n   bonus2 bSkillAtk,"CG_ARROWVULCAN",50;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_barddancer`,`class_third`,`class_third_upper`,`class_third_baby`,`gender`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (26202,'Mirage_Blade_Whip','Mirage Blade Whip','Weapon','Whip',500,150,120,5,1,true,true,true,true,'Female',true,4,150,true,'.@r = getrefine();\nif (.@r>=7)\n   bonus2 bSkillAtk,"CG_ARROWVULCAN",150;\nif (.@r>=9)\n   bonus2 bSkillAtk,"CG_ARROWVULCAN",50;');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_assassin`,`class_third`,`class_third_upper`,`class_third_baby`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28018,'Diva_Katar','Diva Katar','Weapon','Katar',2800,150,250,1,1,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_assassin`,`class_third`,`class_third_upper`,`class_third_baby`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28019,'Mirage_Katar','Mirage Katar','Weapon','Katar',2800,150,250,5,1,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_alchemist`,`job_blacksmith`,`job_crusader`,`job_knight`,`class_third`,`class_third_upper`,`class_third_baby`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28117,'Diva_Twohand_Axe','Diva Twohand Axe','Weapon','2hAxe',4000,320,200,1,1,true,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_alchemist`,`job_blacksmith`,`job_crusader`,`job_knight`,`class_third`,`class_third_upper`,`class_third_baby`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28118,'Mirage_Twohand_Axe','Mirage Twohand Axe','Weapon','2hAxe',4000,320,200,5,1,true,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');


REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_rebellion`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28227,'Diva_Rifle','Diva Rifle','Weapon','Rifle',850,170,9,1,true,true,true,4,150,true,'.@r = getrefine();\nbonus2 bSkillAtk,"RL_HAMMER_OF_GOD",(readparam(bInt)/10)*7;\nif (readparam(bInt)>=110)\n   bonus2 bSkillAtk,"RL_HAMMER_OF_GOD",30;\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_rebellion`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28228,'Mirage_Rifle','Mirage Rifle','Weapon','Rifle',850,170,9,1,true,true,true,4,150,true,'.@r = getrefine();\nbonus bBaseAtk,2*getskilllv("GS_SNAKEEYE");\nbonus2 bSkillAtk,"RL_HAMMER_OF_GOD",(readparam(bInt)/10)*7;\nif (readparam(bInt)>=110)\n   bonus2 bSkillAtk,"RL_HAMMER_OF_GOD",30;\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_rebellion`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28229,'Diva_Gatling_Gun','Diva Gatling Gun','Weapon','Gatling',2500,120,9,1,true,true,true,4,150,true,'.@r = getrefine();\nbonus2 bSkillAtk,"RL_R_TRIP",(readparam(bAgi)/10)*7;\nif (readparam(bAgi)>=110)\n   bonus2 bSkillAtk,"RL_R_TRIP",30;\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_rebellion`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28230,'Mirage_Gatling_Gun','Mirage Gatling Gun','Weapon','Gatling',2500,120,9,1,true,true,true,4,150,true,'.@r = getrefine();\nbonus bBaseAtk,2*getskilllv("GS_SNAKEEYE");\nbonus2 bSkillAtk,"RL_R_TRIP",(readparam(bAgi)/10)*7;\nif (readparam(bAgi)>=110)\n   bonus2 bSkillAtk,"RL_R_TRIP",30;\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_rebellion`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28231,'Diva_Launcher','Diva Launcher','Weapon','Grenade',1400,210,9,1,true,true,true,4,150,true,'.@r = getrefine();\nbonus2 bSkillAtk,"RL_D_TAIL",(readparam(bLuk)/10)*7;\nif (readparam(bLuk)>=110)\n   bonus2 bSkillAtk,"RL_D_TAIL",30;\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_rebellion`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28232,'Mirage_Launcher','Mirage Launcher','Weapon','Grenade',1400,210,9,1,true,true,true,4,150,true,'.@r = getrefine();\nbonus bBaseAtk,2*getskilllv("GS_SNAKEEYE");\nbonus2 bSkillAtk,"RL_D_TAIL",(readparam(bLuk)/10)*7;\nif (readparam(bLuk)>=110)\n   bonus2 bSkillAtk,"RL_D_TAIL",30;\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_rebellion`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28233,'Diva_Shotgun','Diva Shotgun','Weapon','Shotgun',3000,180,9,1,true,true,true,4,150,true,'.@r = getrefine();\nbonus bSplashRange,1;\nbonus2 bSkillAtk,"RL_SLUGSHOT",(readparam(bStr)/10)*7;\nif (readparam(bStr)>=110)\n   bonus2 bSkillAtk,"RL_SLUGSHOT",30;\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_rebellion`,`location_left_hand`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28234,'Mirage_Shotgun','Mirage Shotgun','Weapon','Shotgun',3000,180,9,1,true,true,true,4,150,true,'.@r = getrefine();\nbonus bSplashRange,1;\nbonus2 bSkillAtk,"RL_SLUGSHOT",(readparam(bStr)/10)*7;\nbonus bBaseAtk,2*getskilllv("GS_SNAKEEYE");\nif (readparam(bStr)>=110)\n   bonus2 bSkillAtk,"RL_SLUGSHOT",30;\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_priest`,`job_sage`,`job_stargladiator`,`class_third`,`class_third_upper`,`class_third_baby`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28609,'Diva_Book','Diva Book','Weapon','Book',800,120,140,1,1,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nbonus bUnbreakableWeapon;\nbonus bHealPower,2*.@r;\nif (.@r>=7)\n   bonus bMatkRate,4;\nif (.@r>=9)\n   bonus bMatkRate,4;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_priest`,`job_sage`,`job_stargladiator`,`class_third`,`class_third_upper`,`class_third_baby`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28610,'Mirage_Book','Mirage Book','Weapon','Book',800,120,140,5,1,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nbonus bUnbreakableWeapon;\nbonus bHealPower,2*.@r;\nif (.@r>=7)\n   bonus bMatkRate,4;\nif (.@r>=9)\n   bonus bMatkRate,4;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`location_right_hand`,`flag_buyingstore`,`flag_dropeffect`,`script`) VALUES (4535,'Sealed_Rand_Card','Sealed Randgris Card','Card',20,10,true,true,'CLIENT','bonus bUnbreakableWeapon;\nbonus2 bAddClass,Class_All,(getrefine()>=15?8:5);\nbonus3 bAutoSpell,"SA_DISPELL",1,25;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`location_armor`,`flag_buyingstore`,`flag_dropeffect`,`script`) VALUES (4542,'SLD_Detale_Card','Sealed Detale Card','Card',20,10,true,true,'CLIENT','bonus bMdef,-20;\nbonus2 bResEff,Eff_Freeze,(getrefine()>=15?6000:4000);\nbonus5 bAutoSpellWhenHit,"SA_LANDPROTECTOR",1,35,BF_MAGIC,0;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`location_armor`,`flag_buyingstore`,`flag_dropeffect`,`script`) VALUES (4547,'Upd_Byorgue_Card','Enhanced Byorgue Card','Card',20,10,true,true,'CLIENT','if (BaseJob == Job_Rogue) {\n   bonus bMatkRate,10;\n   bonus2 bAddClass,Class_All,10;\n}\nbonus bMaxHPrate,getrefine()/2;\nbonus3 bAddEffOnSkill,"SC_BODYPAINT",Eff_Stun,1000;');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_alchemist`,`job_archer`,`job_assassin`,`job_barddancer`,`job_blacksmith`,`job_crusader`,`job_hunter`,`job_kagerouoboro`,`job_knight`,`job_mage`,`job_merchant`,`job_ninja`,`job_novice`,`job_rogue`,`job_sage`,`job_soullinker`,`job_supernovice`,`job_swordman`,`job_thief`,`job_wizard`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28708,'Dagger_of_Trust','Thunder Sword','Weapon','Dagger',1000,150,1,3,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,3,50,true,'.@r = getrefine();\nbonus bAtkEle,Ele_Wind;\nif (.@r>=7) {\n .@val = 10;\n if (.@r>=9)\n .@val += 15;\n bonus2 bAddEle,Ele_Water,.@val;\n bonus2 bAddRace,RC_Fish,.@val;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_alchemist`,`job_archer`,`job_assassin`,`job_barddancer`,`job_blacksmith`,`job_crusader`,`job_hunter`,`job_kagerouoboro`,`job_knight`,`job_mage`,`job_merchant`,`job_ninja`,`job_novice`,`job_rogue`,`job_sage`,`job_soullinker`,`job_supernovice`,`job_swordman`,`job_thief`,`job_wizard`,`class_third`,`class_third_upper`,`class_third_baby`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28722,'Diva_Dagger','Diva Dagger','Weapon','Dagger',600,120,120,1,1,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_alchemist`,`job_archer`,`job_assassin`,`job_barddancer`,`job_blacksmith`,`job_crusader`,`job_hunter`,`job_kagerouoboro`,`job_knight`,`job_mage`,`job_merchant`,`job_ninja`,`job_novice`,`job_rogue`,`job_sage`,`job_soullinker`,`job_supernovice`,`job_swordman`,`job_thief`,`job_wizard`,`class_third`,`class_third_upper`,`class_third_baby`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (28723,'Mirage_Dagger','Mirage Dagger','Weapon','Dagger',600,120,120,5,1,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_crusader`,`job_knight`,`class_third`,`class_third_upper`,`class_third_baby`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (32001,'Diva_Spear','Diva Spear','Weapon','1hSpear',1800,150,110,3,1,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`magic_attack`,`range`,`slots`,`job_crusader`,`job_knight`,`class_third`,`class_third_upper`,`class_third_baby`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (32002,'Mirage_Spear','Mirage Spear','Weapon','1hSpear',1800,150,110,5,1,true,true,true,true,true,true,4,150,true,'.@r = getrefine();\nif (.@r>=7) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}\nif (.@r>=9) {\n   bonus bBaseAtk,30;\n   bonus bHit,5;\n}');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`subtype`,`weight`,`attack`,`range`,`slots`,`job_novice`,`job_supernovice`,`location_right_hand`,`weapon_level`,`equip_level_min`,`refineable`,`script`) VALUES (500007,'Ep172_1h_Sword','Hypocrisy Machine','Weapon','1hSword',3000,250,1,3,true,true,true,4,150,true,'.@r = getrefine();\nbonus bUnbreakableWeapon;\nbonus bShortAtkRate,3*(.@r/2);\nbonus bCritical,2*(.@r/3);\nif (.@r>=7)\n bonus bAspdRate,20;\nif (.@r>=9) {\n bonus2 bAddSize,Size_Small,25;\n bonus2 bAddSize,Size_Large,25;\n}\nif (.@r>=11)\n skill "KN_BOWLINGBASH",getskilllv("SM_SWORD");');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`flag_uniqueid`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_nosell`,`trade_nocart`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (17176,'Boarding_Halter_Box3','Halter Lead Box[Trial]','Cash',20,true,100,true,true,true,true,true,true,true,'rentitem 12622,259200;');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_container`,`script`) VALUES (22571,'Easter_Egg','Easter Egg','Delayconsume',10,10,true,'getgroupitem(IG_EASTER_EGG);');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_container`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (22708,'Pitapat_Box','Thrilling Box','Usable',10,100,true,100,true,true,true,true,true,true,true,'getgroupitem(IG_PITAPAT_BOX);');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`flag_container`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_nocart`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (22870,'Xmas_Package_14','Christmas Package','Usable',10,true,100,true,true,true,true,true,true,'getgroupitem(IG_XMAS_PACKAGE_14);');

REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`location_right_hand`,`flag_buyingstore`,`flag_dropeffect`,`script`) VALUES (4603,'CorruptionRoot_Card','Corruption Root Card','Card',20,10,true,true,'CLIENT','bonus bBaseAtk,20;\nbonus5 bAutoSpell,"NPC_WIDESTONE",1,50,BF_SHORT,0;\nbonus5 bAutoSpell,"NPC_WIDESLEEP",1,50,BF_SHORT,0;\nbonus5 bAutoSpell,"NPC_WIDECURSE",1,50,BF_SHORT,0;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`location_right_hand`,`flag_buyingstore`,`flag_dropeffect`,`script`) VALUES (4604,'CorruptionRootH_Card','Realized Corruption Root Card','Card',20,10,true,true,'CLIENT','bonus bBaseAtk,30;\nbonus5 bAutoSpell,"NPC_WIDESTONE",2,50,BF_SHORT,0;\nbonus5 bAutoSpell,"NPC_WIDESLEEP",2,50,BF_SHORT,0;\nbonus5 bAutoSpell,"NPC_WIDECURSE",2,50,BF_SHORT,0;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`location_right_hand`,`flag_dropeffect`,`script`) VALUES (27031,'Labyrinth_Bapho_Card','Labyrinth Baphomet Card','Card',20,10,true,'CLIENT','bonus2 bAddClass,Class_All,10;');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`location_right_hand`,`flag_dropeffect`,`script`) VALUES (27032,'Labyrinth_Dra_Card','Labyrinth Dracula Card','Card',20,10,true,'CLIENT','bonus2 bAddClass,Class_All,10;');

REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (603,'Old_Blue_Box','Old Blue Box','Usable',10000,200,true,true,'getrandgroupitem(IG_BlueBox,1);');

REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (616,'Old_Card_Album','Old Card Album','Usable',10000,50,true,true,'getrandgroupitem(IG_CardAlbum,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (617,'Old_Violet_Box','Old Purple Box','Usable',10000,200,true,true,'getrandgroupitem(IG_VioletBox,1);');

REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (644,'Gift_Box','Gift Box','Usable',1000,200,true,true,'getrandgroupitem(IG_GiftBox,1);');

REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (664,'Gift_Box_1','Gift Box','Usable',1000,200,true,true,'getrandgroupitem(IG_GiftBox_1,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (665,'Gift_Box_2','Gift Box','Usable',1000,200,true,true,'getrandgroupitem(IG_GiftBox_2,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (666,'Gift_Box_3','Gift Box','Usable',1000,200,true,true,'getrandgroupitem(IG_GiftBox_3,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (667,'Gift_Box_4','Gift Box','Usable',1000,200,true,true,'getrandgroupitem(IG_GiftBox_4,1);');

REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_container`,`script`) VALUES (12023,'Giftbox_China','Wrapped Box','Usable',1000,200,true,'getrandgroupitem(IG_GiftBoxChina,1);');

REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_container`,`script`) VALUES (12025,'Egg_Boy','Dano Festival Egg','Usable',1000,200,true,'getrandgroupitem(IG_EggBoy,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_container`,`script`) VALUES (12026,'Egg_Girl','Dano Festival Egg','Usable',1000,200,true,'getrandgroupitem(IG_EggGirl,1);');

REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`flag_container`,`script`) VALUES (12038,'Lotto_Box04','Lotto Box 04','Usable',20,true,'getrandgroupitem(IG_LottoBox,1);');

REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (12104,'Random_Quiver','Random Quiver','Usable',10000,200,true,true,'getrandgroupitem(IG_Quiver,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (12105,'Set_Of_Taiming_Item','Taming Gift Set','Usable',10000,200,true,true,'getrandgroupitem(IG_Taming,1);\ngetrandgroupitem(IG_Taming,1);\ngetrandgroupitem(IG_Taming,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (12106,'Accessory_Box','Jewelry Box','Usable',10000,200,true,true,'getrandgroupitem(IG_Accesory,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (12107,'Wrapped_Mask','Wrapped Mask','Usable',10000,200,true,true,'getrandgroupitem(IG_Mask,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (12108,'Bundle_Of_Magic_Scroll','Scroll Package','Usable',10000,200,true,true,'getrandgroupitem(IG_Scroll,1);\ngetrandgroupitem(IG_Scroll,1);\ngetrandgroupitem(IG_Scroll,1);\ngetrandgroupitem(IG_Scroll,1);\ngetrandgroupitem(IG_Scroll,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_deadbranch`,`script`) VALUES (12109,'Poring_Box','Poring Box','Usable',10000,200,true,true,'monster "this",-1,-1,"--ja--",-1-MOBG_PORING_BOX,1,"";');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (12110,'First_Aid_Kit','First Aid Kit','Usable',10000,200,true,true,'getrandgroupitem(IG_FirstAid,1);\ngetrandgroupitem(IG_FirstAid,1);\ngetrandgroupitem(IG_FirstAid,1);\ngetrandgroupitem(IG_FirstAid,1);\ngetrandgroupitem(IG_FirstAid,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (12111,'Food_Package','Bundle of Food','Usable',10000,200,true,true,'getrandgroupitem(IG_FoodBag,1);\ngetrandgroupitem(IG_FoodBag,1);\ngetrandgroupitem(IG_FoodBag,1);');

REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (12130,'Cookie_Bag','Cookie Bag','Usable',2,70,true,true,'getrandgroupitem(IG_CookieBag,1);\ngetrandgroupitem(IG_CookieBag,1);\ngetrandgroupitem(IG_CookieBag,1);');

REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_container`,`script`) VALUES (12186,'Red_Box','Old Red Box','Usable',50000,200,true,'getrandgroupitem(IG_RedBox,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_container`,`script`) VALUES (12187,'Green_Box','Old Green Box','Usable',50000,200,true,'getrandgroupitem(IG_GreenBox,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_container`,`script`) VALUES (12189,'Red_Box_','Old Red Box','Usable',50000,200,true,'getrandgroupitem(IG_RedBox_2,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (12194,'Hometown_Gift','Hometown Gift','Usable',20,200,true,true,'getrandgroupitem(IG_HometownGift,1);\ngetrandgroupitem(IG_HometownGift,1);\ngetrandgroupitem(IG_HometownGift,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_container`,`script`) VALUES (12240,'Old_Yellow_Box','Old Yellow Box','Usable',20,200,true,'getrandgroupitem(IG_YellowBox,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_container`,`script`) VALUES (12244,'Old_Gift_Box','Old Gift Box','Usable',20,200,true,'getrandgroupitem(IG_OldGiftBox,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (12246,'Magic_Card_Album','Mystical Card Album','Usable',10000,50,true,true,'getrandgroupitem(IG_MagicCardAlbum,1);');

REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_container`,`script`) VALUES (12248,'Masquerade_Ball_Box','Fancy Ball Box','Usable',20,10,true,'getrandgroupitem(IG_Masquerade,1);');

REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_container`,`script`) VALUES (12281,'Tresure_Box_WoE','Event Treasure Box','Usable',20,150,true,'getrandgroupitem(IG_Tresure_Box_WoE,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`flag_container`,`script`) VALUES (12286,'Masquerade_Ball_Box2','Masquerade Ball Box2','Usable',10,true,'getrandgroupitem(IG_Masquerade_2,1);');

REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`flag_container`,`script`) VALUES (12334,'Cherish_Box','Treasure Edition Helm Box','Usable',10,true,'getrandgroupitem(IG_Cherish_Box,1);');

REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`flag_container`,`script`) VALUES (12339,'Cherish_Box_Ori','Treasure Edition Box','Usable',10,true,'getrandgroupitem(IG_Cherish_Box_Ori,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (12355,'Xmas_Gift','Xmas Gift','Usable',2,100,true,true,'getrandgroupitem(IG_Xmas_Gift,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_buyingstore`,`flag_container`,`script`) VALUES (12356,'Louise_Costume_Box','Louise Costume Box','Usable',2,100,true,true,'getrandgroupitem(IG_Louise_Costume_Box,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`flag_container`,`script`) VALUES (12702,'Old_Bleu_Box','Old Navy Box','Usable',200,true,'getrandgroupitem(IG_BleuBox,1);\ngetrandgroupitem(IG_BleuBox,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`price_buy`,`weight`,`flag_container`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_nocart`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (12714,'Easter_Scroll','Easter Scroll','Usable',1,10,true,100,true,true,true,true,true,true,'getrandgroupitem(IG_Easter_Scroll,1);');
REPLACE INTO `item_db` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`flag_container`,`script`) VALUES (14596,'Pierre_Treasurebox','Pierre\'s Treasure Box','Usable',100,true,'getrandgroupitem(IG_Pierre_Treasurebox,1);\ngetrandgroupitem(IG_Pierre_Treasurebox,1);\ngetrandgroupitem(IG_Pierre_Treasurebox,1);\ngetrandgroupitem(IG_Pierre_Treasurebox,1);\ngetrandgroupitem(IG_Pierre_Treasurebox,1);\ngetrandgroupitem(IG_Pierre_Treasurebox,1);');